### PR TITLE
Release/1.0.2

### PR DESCRIPTION
**Pull request by amalloy**
@dirtyvagabond @mavericklou Any comments on this, or anything else you'd like in 1.0.2 before I merge it?

### CODE REVIEW

**Comment by dirtyvagabond** [comment]
LGTM!

**Comment by amalloy** [comment]
@dirtyvagabond What needs to happen to get this release published? I can deploy to clojars but I gather we have some other place to publish the executable jar?

**Comment by dirtyvagabond** [comment]
Yes. I'll take care of it. Thanks @amalloy

**Comment by potash** [comment]
Any progress on making a release of this? I'm currently stuck on 0.1.6 due to #201.

**Comment by dirtyvagabond** [comment]
Hi @potash , it's not currently a priority. Are you able to build from develop?

**Comment by potash** [comment]
Okay. Yes, I was able to build from develop. I can finally clean up my Drakefiles from unnecessary 0.1.6 work-arounds! And start-up time is improved! Great work. Thanks everyone.

**Pull request merged**
